on:
  pull_request:
jobs:
  fleximod-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # oldest supported and latest supported
        python-version: ["3.8", "3.x"]
    steps:
      - id: checkout-CESM
        uses: actions/checkout@v5
      - id: run-fleximod
        run: |
          $GITHUB_WORKSPACE/bin/git-fleximod update -o
          echo
          echo "Update complete, checking status"
          echo
          $GITHUB_WORKSPACE/bin/git-fleximod test
      - id: check-cleanliness
        run: |
          echo
          echo "Checking if git fleximod matches expected externals"
          echo
          git add . && git diff --exit-code && git diff --cached --exit-code
